selector:
	bash ./scripts/selector.sh

build_image:
	bash ./scripts/build.sh

push_image:
	bash ./scripts/push.sh

run_debug:
	bash ./scripts/debug.sh

run_qt:
	bash ./scripts/qt.sh

run_gui:
	bash ./scripts/gui.sh

run_shell:
	bash ./scripts/shell.sh
